export class EntityTypes {
    static TYPE_DEFAULT_OBJECT = 'DEFAULT_OBJECT';
    static PLAYER = 'PLAYER';
    static INTERFACE_OBJECT = 'INTERFACE_OBJECT';
    static PROJECTILE = 'PROJECTILE';
    static PROJECTILE_PLAYER = 'PROJECTILE_PLAYER';
    static PROJECTILE_ENEMY = 'PROJECTILE_ENEMY';
    static ENEMY = 'ENEMY';
    static EXPLOSION = 'EXPLOSION';
    static COLLECTIBLE = 'COLLECTIBLE';
}
