export class EventType {
    static MOVEMENT = 'movement';
    static GAME_TICK = 'game.tick';
    static FPS_TICK = 'game.fps.tick';
    static PLAYER_CREATE = 'player.create';
    static PLAYER_RENDER = 'player.render';
    static PLAYER_UPDATE = 'player.update';
    static PLAYER_ROTATE = 'player.rotate';
    static RENDER_MINIMAP = 'render.minimap';
    static UPDATE_MINIMAP = 'update.minimap';
    static ACTIVATE_SLOT = 'slot.activate';
    static OBJECT_CREATED = 'object.created';
    static REMOVE_OBJECT = 'remove.object';
    static VISIBLE_OBJECTS_TICK = 'visible.objects.tick';
    static ENEMY_DESTROYED = 'enemy.destroyed';
    static PROJECTILE_HIT = 'projectile.hit';
    static UI_ELEMENT_CREATE = 'ui.element.create';
    static TOGGLE_PAUSE = 'toggle.pause';
    static TOGGLE_DEBUG = 'toggle.debug';
    static TOGGLE_SLOWMO = 'toggle.slowmo';
    static SLOWMO_CHANGE = 'slowmo.change';
    static PROJECTILE_RENDER = 'projectile.render';
    static GAME_STATE_CHANGE = 'game.state.change';
    static PLAYER_DESTROYED = 'player.destroyed';
    static RENDER_COLLISION = 'render.collision';
    static GAME_SPEED_CHANGE = 'game.speed.change';
    static DEBUG_MODE_CHANGE = 'debug.mode.change';

}
